dist: trusty

language: node_js
node_js:
  - 6  # Because `protractor@5.4.1` requires 6.9+.
  - 10

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
    - "$HOME/.npm"

  script:
   —  echo “Deploy!!”
  install:
   —  npm install -g firebase-tools
  after_success:
   —  firebase deploy — project globalconnect-3f3f5 1/XbDy8VQQloxTkYQcJWKiLDwaAByGbvTVZZ2VKeZg7tY


